commerce_payment.commerce_payment_gateway.plugin.offsite_redsys:
  type: commerce_payment_gateway_configuration
  mapping:
    url_test:
      type: string
      label: 'The Url test'
    url_live:
      type: string
      label: 'The Url live'
    signatureversion:
      type: string
      label: 'The signature version'
    signature:
      type: string
      label: 'The signature'
    merchant_url:
      type: string
      label: 'The Merchant Url'
    merchant_code:
      type: string
      label: 'The Merchant Code'
    terminal:
      type: string
      label: 'The Terminal Code'
    currency:
      type: integer
      label: 'The currency'
    transaction_type:
      type: integer
      label: 'The Transaction Type'
