commerce_mailing_products.type.*:
  type: config_entity
  label: 'Mailing type'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    send_type:
      type: integer
      label: 'Send Type'