<?php

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function commerce_mailing_products_theme()
{
  return [
    'commerce_mailing_products' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for commerce_mailing_products templates.
 *
 * Default template: commerce-mailing-products.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the commerce_mailing_products information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_commerce_mailing_products(array &$variables)
{
  /*foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }*/
}
